import type { IdValue, NavItem, ProjectProps } from "./interface";
import dummy_project1 from "../assets/image/dummy_project1.png";
import dummy_project2 from "../assets/image/dummy_project2.png";
import dummy_project3 from "../assets/image/dummy_project3.png";

const navItems: NavItem[] = [
  { id: 1, label: "HOME", hasArrow: false, route: "/" },
  { id: 2, label: "OFFICES", hasArrow: true, route: "/offices" },
  { id: 3, label: "IT", hasArrow: true, route: "/it" },
  { id: 4, label: "PEOPLE TEAM", hasArrow: true, route: "/people-team" },
  { id: 5, label: "PROJECTS", hasArrow: true, route: "/projects" },
];

const stateList: IdValue[] = [
  { id: 1, value: "Andhra Pradesh" },
  { id: 2, value: "Arunachal Pradesh" },
  { id: 3, value: "Assam" },
  { id: 4, value: "Bihar" },
  { id: 5, value: "Chhattisgarh" },
  { id: 6, value: "Goa" },
  { id: 7, value: "Gujarat" },
  { id: 8, value: "Haryana" },
  { id: 9, value: "Himachal Pradesh" },
  { id: 10, value: "Jharkhand" },
  { id: 11, value: "Karnataka" },
  { id: 12, value: "Kerala" },
  { id: 13, value: "Madhya Pradesh" },
  { id: 14, value: "Maharashtra" },
  { id: 15, value: "Manipur" },
  { id: 16, value: "Meghalaya" },
  { id: 17, value: "Mizoram" },
  { id: 18, value: "Nagaland" },
  { id: 19, value: "Odisha" },
  { id: 20, value: "Punjab" },
  { id: 21, value: "Rajasthan" },
  { id: 22, value: "Sikkim" },
  { id: 23, value: "Tamil Nadu" },
  { id: 24, value: "Telangana" },
  { id: 25, value: "Tripura" },
  { id: 26, value: "Uttar Pradesh" },
  { id: 27, value: "Uttarakhand" },
  { id: 28, value: "West Bengal" },
];

const projects: ProjectProps[] = [
  {
    projectId: 1,
    projectIcon: dummy_project1,
    status: "Ongoing",
    statusId: 1,
    lastUpdate: "2026-01-15T09:14:00Z",
    projectName: "Skyline 400kV Transmission Hub",
    location: {
      city: "Mumbai",
      cityId: 101,
      state: "Maharashtra",
      stateId: 27,
      country: "India",
      countryId: 91,
    },
    reportLink: "/projects/1",
    image: "/images/projects/skyline-400kv.jpg",
    voltage: "400kV",
    voltageLevel: 400,
    category: "Transmission Substation",
    categoryId: 10,
    client: "Power Grid Corporation of India",
    clientId: 501,
    projectCode: "PRJ-2024-001",
    duration: { startDate: "2024-01-01", endDate: "2025-12-31" },
    tags: ["Transmission Substation", "400kV"],
    isOngoing: true,
    latestPhotoLabel: "Latest Site Photo",
  },

  {
    projectId: 2,
    projectIcon: dummy_project2,
    status: "Completed",
    statusId: 2,
    lastUpdate: "2024-11-12T16:35:00Z",
    projectName: "Riverside AIS Distribution",
    location: {
      city: "Pune",
      cityId: 102,
      state: "Maharashtra",
      stateId: 27,
      country: "India",
      countryId: 91,
    },
    reportLink: "/projects/2",
    image: "/images/projects/riverside-ais.jpg",
    voltage: "66/11kV",
    voltageLevel: 66,
    category: "AIS Substation",
    categoryId: 11,
    client: "MSEDCL – Maharashtra State",
    clientId: 502,
    projectCode: "PRJ-2024-002",
    duration: { startDate: "2023-03-01", endDate: "2024-11-30" },
    tags: ["AIS Substation", "66/11kV"],
    isOngoing: false,
    latestPhotoLabel: "Latest Site Photo",
  },

  {
    projectId: 3,
    projectIcon: dummy_project3,
    status: "On Hold",
    statusId: 3,
    lastUpdate: "2026-03-01T11:20:00Z",
    projectName: "Metro North GIS Facility",
    location: {
      city: "Bengaluru",
      cityId: 103,
      state: "Karnataka",
      stateId: 29,
      country: "India",
      countryId: 91,
    },
    reportLink: "/projects/3",
    image: "/images/projects/metro-gis.jpg",
    voltage: "2x6.3 MVA",
    voltageLevel: 6,
    category: "GIS Substation",
    categoryId: 12,
    client: "BESCOM – Bangalore Electricity",
    clientId: 503,
    projectCode: "PRJ-2024-003",
    duration: { startDate: "2024-06-01", endDate: "2026-03-31" },
    tags: ["GIS Substation", "2x6.3 MVA"],
    isOngoing: false,
    latestPhotoLabel: "Latest Site Photo",
  },

  {
    projectId: 4,
    projectIcon: dummy_project1,
    status: "Ongoing",
    statusId: 1,
    lastUpdate: "2026-03-02T07:55:00Z",
    projectName: "Harbor Transmission Corridor",
    location: {
      city: "Chennai",
      cityId: 104,
      state: "Tamil Nadu",
      stateId: 33,
      country: "India",
      countryId: 91,
    },
    reportLink: "/projects/4",
    image: "/images/projects/harbor-line.jpg",
    voltage: "400kV",
    voltageLevel: 400,
    category: "Substation & Transmission Line",
    categoryId: 13,
    client: "NTPC Limited",
    clientId: 504,
    projectCode: "PRJ-2024-004",
    duration: { startDate: "2024-09-01", endDate: "2026-08-31" },
    tags: ["Transmission Line", "400kV"],
    isOngoing: true,
    latestPhotoLabel: "Latest Site Photo",
  },

  {
    projectId: 5,
    projectIcon: dummy_project2,
    status: "Ongoing",
    statusId: 1,
    lastUpdate: "2026-03-02T08:30:00Z",
    projectName: "Northgate GIS Compact Unit",
    location: {
      city: "Coimbatore",
      cityId: 105,
      state: "Tamil Nadu",
      stateId: 33,
      country: "India",
      countryId: 91,
    },
    reportLink: "/projects/5",
    image: "/images/projects/northgate-gis.jpg",
    voltage: "66/11kV",
    voltageLevel: 66,
    category: "GIS Substation",
    categoryId: 12,
    client: "TNEB – Tamil Nadu Electricity Board",
    clientId: 505,
    projectCode: "PRJ-2023-018",
    duration: { startDate: "2023-04-01", endDate: "2025-06-30" },
    tags: ["GIS Substation", "66/11kV"],
    isOngoing: true,
    latestPhotoLabel: "Latest Site Photo",
  },

  {
    projectId: 6,
    projectIcon: dummy_project3,
    status: "Completed",
    statusId: 2,
    lastUpdate: "2023-10-18T16:10:00Z",
    projectName: "Sunvalley AIS Grid Node",
    location: {
      city: "Surat",
      cityId: 106,
      state: "Gujarat",
      stateId: 24,
      country: "India",
      countryId: 91,
    },
    reportLink: "/projects/6",
    image: "/images/projects/sunvalley-ais.jpg",
    voltage: "2x6.3 MVA",
    voltageLevel: 6,
    category: "AIS Substation",
    categoryId: 11,
    client: "DGVCL – Dakshin Gujarat",
    clientId: 506,
    projectCode: "PRJ-2022-045",
    duration: { startDate: "2022-02-01", endDate: "2023-10-31" },
    tags: ["AIS Substation", "2x6.3 MVA"],
    isOngoing: false,
    latestPhotoLabel: "Latest Site Photo",
  },

  {
    projectId: 7,
    projectIcon: dummy_project1,
    status: "Ongoing",
    statusId: 1,
    lastUpdate: "2026-03-01T14:00:00Z",
    projectName: "Oakwood Transmission Line",
    location: {
      city: "Ahmedabad",
      cityId: 107,
      state: "Gujarat",
      stateId: 24,
      country: "India",
      countryId: 91,
    },
    reportLink: "/projects/7",
    image: "/images/projects/oakwood-line.jpg",
    voltage: "66/11kV",
    voltageLevel: 66,
    category: "Substation & Transmission Line",
    categoryId: 13,
    client: "PGVCL – Paschim Gujarat",
    clientId: 507,
    projectCode: "PRJ-2024-011",
    duration: { startDate: "2024-07-01", endDate: "2025-12-31" },
    tags: ["Transmission Line", "66/11kV"],
    isOngoing: true,
    latestPhotoLabel: "Latest Site Photo",
  },

  {
    projectId: 8,
    projectIcon: dummy_project1,
    status: "Completed",
    statusId: 2,
    lastUpdate: "2024-09-28T10:05:00Z",
    projectName: "Emerald GIS Switching Station",
    location: {
      city: "Hyderabad",
      cityId: 108,
      state: "Telangana",
      stateId: 36,
      country: "India",
      countryId: 91,
    },
    reportLink: "/projects/8",
    image: "/images/projects/emerald-gis.jpg",
    voltage: "400kV",
    voltageLevel: 400,
    category: "GIS Substation",
    categoryId: 12,
    client: "TSSPDCL – Telangana Southern",
    clientId: 508,
    projectCode: "PRJ-2023-029",
    duration: { startDate: "2023-01-01", endDate: "2024-09-30" },
    tags: ["GIS Substation", "400kV"],
    isOngoing: false,
    latestPhotoLabel: "Latest Site Photo",
  },

  {
    projectId: 9,
    projectIcon: dummy_project2,
    status: "On Hold",
    statusId: 3,
    lastUpdate: "2026-02-27T09:40:00Z",
    projectName: "Lakeview Transmission Hub",
    location: {
      city: "Lucknow",
      cityId: 109,
      state: "Uttar Pradesh",
      stateId: 9,
      country: "India",
      countryId: 91,
    },
    reportLink: "/projects/9",
    image: "/images/projects/lakeview-hub.jpg",
    voltage: "2x6.3 MVA",
    voltageLevel: 6,
    category: "Transmission Substation",
    categoryId: 10,
    client: "UPPCL – Uttar Pradesh Power",
    clientId: 509,
    projectCode: "PRJ-2024-007",
    duration: { startDate: "2024-10-01", endDate: "2027-04-30" },
    tags: ["Transmission Substation", "2x6.3 MVA"],
    isOngoing: false,
    latestPhotoLabel: "Latest Site Photo",
  },
];

export { navItems, stateList, projects };
